language: node_js
node_js:
  - "v8.9.0"

before_install:
  - npm update -g npm

env:
  global:
    - DOCKER_REPO=quay.io/alegion/swagger-combined
    - DOCKER_IMAGE=$DOCKER_REPO:build-$TRAVIS_BUILD_NUMBER

script:
  - docker build --tag $DOCKER_IMAGE .
